global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'jira'
    scrape_interval: 1m
    metrics_path: '/plugins/servlet/prometheus/metrics'
    params:
      token: ['project1']
    static_configs:
      - targets: ['jira:8080']

  - job_name: 'grafana'
    scrape_interval: 1m
    static_configs:
      - targets: ['grafana:3000']