stages:
  - install
  - build
  - test
  - docker
  - static
  - dast
  
install-job:
  stage: install
  image: 
    name: node:14-alpine
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

build-job:
  stage: build
  image: 
    name: node:14-alpine
  script:
    - node app.js
    - echo "App has been built"
  artifacts:
    paths:
      - node_modules/


test-job:
  stage: test
  image: 
    name: node:14-alpine
  script:
    - npm install mocha -g
    - mocha ./test/test.js
    - echo "App has been tested"
  artifacts:
    paths:
      - node_modules/test/

dind-build:
  stage: docker

  image:
    name: docker:stable
    
  services:
   - name: docker:dind
     alias: dockerdaemon
     command: ["--insecure-registry=a16762aee6ff5485281190329b6c4efd-433642122.us-east-1.elb.amazonaws.com"]
  variables:
    DOCKER_HOST: tcp://dockerdaemon:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - echo "Welcome message"
    - docker login -u alper.cetin -p AlperCetin2023 https://a16762aee6ff5485281190329b6c4efd-433642122.us-east-1.elb.amazonaws.com/
    - docker build -t "image2:dind" .
    - docker tag image2:dind a16762aee6ff5485281190329b6c4efd-433642122.us-east-1.elb.amazonaws.com/internship/alper_gitlabci_case2
    - docker push a16762aee6ff5485281190329b6c4efd-433642122.us-east-1.elb.amazonaws.com/internship/alper_gitlabci_case2:latest

alper-sonarqube-project:
  stage: static
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  services:
    - name: sonarsource/sonar-scanner-cli:latest
      command: ["--insecure-registry=a13afa3e4a01a4c9892e92550e9aa2bf-1025562149.us-east-1.elb.amazonaws.com"]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
    GIT_DEPTH: "0" 
    
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner -X -Djavax.net.debug=all -Dsonar.sources=. -Dsonar.host.url=http://a13afa3e4a01a4c9892e92550e9aa2bf-1025562149.us-east-1.elb.amazonaws.com:9000 -Dsonar.login="alper.cetin" -Dsonar.password="AlperCetin2023"
 
  only:
    - master


dast:
  stage: dast
  dependencies: []
  services:
    - name: "gitlab/gitlab-ee:nightly"
      alias: gitlab
  variables: 
    DAST_WEBSITE: https://172-31-8-143:5000
    DAST_FULL_SCAN_ENABLED: "true"
    DAST_BROWSER_SCAN: "true"
  script:
    - echo "Dast"
