stages:
  - build
  - test
  - docker
  - static
  - artifact
  - dynamic

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true  

build-stage:
  stage: build
  image: maven:3.8-openjdk-11
  script:
    - mvn package -DskipTests=true
    - echo 'Build stage'

test-stage:
  stage: test
  image: maven:3.8-openjdk-11
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  script:
    - mvn $MAVEN_CLI_OPTS verify
    - echo "Test Stage"
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - "**/target"
    reports:
      junit:
        - "**/target/*-reports/TEST-*.xml"
    
docker-stage:
  stage: docker
  image: docker:stable
  services:
   - name: docker:dind
     alias: dockerdaemon
     command: ["--insecure-registry=a16762aee6ff5485281190329b6c4efd-433642122.us-east-1.elb.amazonaws.com"]
  variables:
    DOCKER_HOST: tcp://dockerdaemon:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  only:
    - master
  allow_failure: true
  script:
    - docker login -u alper.cetin -p AlperCetin2023 https://a16762aee6ff5485281190329b6c4efd-433642122.us-east-1.elb.amazonaws.com/
    - docker build -t alper_maven:dind .
    - docker tag alper_maven:dind a16762aee6ff5485281190329b6c4efd-433642122.us-east-1.elb.amazonaws.com/internship/alper_maven_case3
    - docker push a16762aee6ff5485281190329b6c4efd-433642122.us-east-1.elb.amazonaws.com/internship/alper_maven_case3:latest
    - echo "Docker Stage"
  #needs: ["dynamic-stage"]


artifact-stage:
  stage: artifact
  image: maven:3.8-openjdk-11
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  script:
    #- mvn package -DskipTests=true
    - mvn $MAVEN_CLI_OPTS package -DskipTests=true
    - mvn deploy -s ci_settings.xml
    - echo 'Artifact stage'
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - "**/target"
      
static-stage:
  stage: static
  image: 
    name: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
    GIT_DEPTH: "0" 
    SONAR_HOST_URL: http://a13afa3e4a01a4c9892e92550e9aa2bf-1025562149.us-east-1.elb.amazonaws.com:9000
    SONAR_LOGIN: alper.cetin
    SONAR_PASSWORD: AlperCetin2023
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner -X -Dsonar.login="alper.cetin" -Dsonar.password="AlperCetin2023" -Dsonar.sources=. -Dsonar.host.url=http://a13afa3e4a01a4c9892e92550e9aa2bf-1025562149.us-east-1.elb.amazonaws.com:9000 -Dsonar.java.binaries=target/classes   -Dsonar.projectKey=static-stage
  allow_failure: true
  only:
    - master


dynamic-stage:
  stage: dynamic
  image: maven:3.8-openjdk-11
  script:
    - echo 'Dynamic stage'