version: '3'

services:
  jira_node_1:
    depends_on:
      - postgresql
    image: atlassian/jira-software:8.22.0
    networks:
      - jiranet
    volumes:
      - /mnt/c/users/90507/Desktop/before_git/w4_paz/jiradata:/var/atlassian/application-data/jira/shared
    ports:
      - '8082:8080'
      - '8002:8000'
    environment:
      - 'ATL_JDBC_URL=jdbc:postgresql://postgresql:5432/jiradb'
      - 'ATL_JDBC_USER=jira'
      - 'ATL_JDBC_PASSWORD=jirajira'
      - 'ATL_DB_DRIVER=org.postgresql.Driver'
      - 'ATL_DB_TYPE=postgres'
      - 'JVM_MINIMUM_MEMORY=2048m'
      - 'JVM_MAXIMUM_MEMORY=4096m'
      - 'CLUSTERED=true'
      - 'JIRA_NODE_ID=node_1'
      - 'JIRA_SHARED_HOME=/var/atlassian/application-data/jira/shared'
      - 'ENCACHE_PEER_DISCOVERY=default'
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  jira_node_2:
    depends_on:
      - postgresql
    image: atlassian/jira-software:8.22.0
    networks:
      - jiranet
    volumes:
      - /mnt/c/users/90507/Desktop/before_git/w4_paz/jiradata:/var/atlassian/application-data/jira/shared
    ports:
      - '8081:8080'
      - '8001:8000'
    environment:
      - 'ATL_JDBC_URL=jdbc:postgresql://postgresql:5432/jiradb'
      - 'ATL_JDBC_USER=jira'
      - 'ATL_JDBC_PASSWORD=jirajira'
      - 'ATL_DB_DRIVER=org.postgresql.Driver'
      - 'ATL_DB_TYPE=postgres'
      - 'JVM_MINIMUM_MEMORY=2048m'
      - 'JVM_MAXIMUM_MEMORY=4096m'
      - 'CLUSTERED=true'
      - 'JIRA_NODE_ID=node_2'
      - 'JIRA_SHARED_HOME=/var/atlassian/application-data/jira/shared'
      - 'ENCACHE_LISTENER_PORT=40001'
      - 'ENCACHE_OBJECT_PORT=40011'
      - 'ENCACHE_PEER_DISCOVERY=default'
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  postgresql:
    image: postgres:12.0
    networks:
      - jiranet
    volumes:
      - /mnt/c/users/90507/Desktop/before_git/w4_paz/postgresqldata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=jirajira'
      - 'POSTGRES_DB=jiradb'
    


networks:
  jiranet:
    driver: bridge
